### ISSUE TITLE
FastLED issue

### ISSUE THREAD

**Issue by sandman72** [bdring/TWANG32#1]
The current official FastLED 3.1.6 library seems to cause watchdog reset issues here in my ESP32 setup (TTGO 32 R1 board, ESP32 rev1, Arduino ESP32 from Februray). I tried a workaround turning off interrupts during the FastLED .show() call with:

#define FASTLED_ALLOW_INTERRUPTS 0

but unfortunatly that breaks the sound output (loads of clickings during LED updates).
Could you check which versions of the Arduino Core ESP32 and FastLED libraries you are using, assuming everthing is working for you?

BTW: Awesome work! 😃

**Comment by buildlog** [comment]
Sorry to hear you are having problems.

I am using FastLED 3.1.6. I am not sure how to tell the exact version of the ESP32 core, but my latest files are dated 3/14/2018. It runs fine for me on board NodeMCU-32S.  I have compiled it on several computers without issue. I don't know what happens when you choose different boards. What board are you compiling for? Did you change anything else in the firmware, like the #defines for the pins?

The only issue I had during development is that I had to turn off all Interrupts during EEPROM commits.

BTW: I am working on an ESP32 port of Grbl and am having problems with watchdog resets during interrupts. I have not solved that yet.

**Comment by sandman72** [comment]
No, worries... WDT resets are quite common... usually a yield(); here and there will solve that... ;)
I had that issue with the FastLED library on the ESP32 before and could only get it to work stable with turning off interrupts... That usually breaks something else, in this case the sound part. I'll have a look over the weekend if I can find something...

**Comment by sandman72** [comment]
I can confirm that this only happens with WS2812b based strips and their timing requirements. The APA102 strips work fine. No sound issues if you use these. For more infos: https://github.com/FastLED/FastLED/wiki/Interrupt-problems

**Comment by afreeland** [comment]
@bdring seen you actively looking at issues and was hoping you could take a second to read through this?

I am using W2812B LEDs (300 count 16.4') and noticing what appears to be intermittent "freezing" of accelerometer data.  As in, the LEDs and game continue but the input from 🕹️ no longer seems to move the green dot... Until a hard power down.  Also the sound kind of had a pulsing/ticking that is always happening.

Was just curious if the interrupt issue would manifest itself in either of those ways?

Also I am using the esp-wroom-32 DoIt devkit v1 board, if that helps.

Hoping you may have some guidance here, thanks!
